const WS_ADD_MARK = 'WS_ADD_MARK';
const WS_DELETE_MARK = 'WS_DELETE_MARK';
const WS_CHANGE_VISIBLE_MARK = 'WS_CHANGE_VISIBLE_MARK';
const WS_CHANGE_COORDS_MARK = 'WS_CHANGE_COORDS_MARK';
const WS_ADD_MESSAGE_MARK = 'WS_ADD_MESSAGE_MARK';

module.exports = {
  WS_ADD_MARK,
  WS_DELETE_MARK,
  WS_CHANGE_VISIBLE_MARK,
  WS_CHANGE_COORDS_MARK,
  WS_ADD_MESSAGE_MARK,
};
