const ADD_NEW_MARK_TRANSLATE = 'ADD_NEW_MARK_TRANSLATE'
const DELETE_MARK_TRANSLATE = 'DELETE_MARK_TRANSLATE'
const CHANGE_VISIBLE_MARK_TRANSLATE = 'CHANGE_VISIBLE_MARK_TRANSLATE'
const CHANGE_COORDS_MARK_TRANSLATE = 'CHANGE_COORDS_MARK_TRANSLATE'


export {
  ADD_NEW_MARK_TRANSLATE,
  DELETE_MARK_TRANSLATE,
  CHANGE_VISIBLE_MARK_TRANSLATE,
  CHANGE_COORDS_MARK_TRANSLATE
}
