const RECORD_MARKS = 'RECORD_MARKS';
const ADD_MARK = 'ADD_MARK';
const DELETE_MARK = 'DELETE_MARK';
const CHANGE_VISIBLE_MARK = 'CHANGE_VISIBLE_MARK';
const CHANGE_COORDS_MARK = 'CHANGE_COORDS_MARK';
const ADD_MESSAGE_MARK = 'ADD_MESSAGE_MARK';

const RECORD_WEBSOCKET = 'RECORD_WEBSOCKET';

const RECORD_PSD_URL = 'RECORD_PSD_URL';

const RECORD_LAYERS = 'RECORD_PSD_LAYERS';
const CHANGE_VISIBLE_LAYER = 'EDIT_VISIBLE_LAYER';

const WS_ADD_MARK = 'WS_ADD_MARK';
const WS_DELETE_MARK = 'WS_DELETE_MARK';
const WS_CHANGE_VISIBLE_MARK = 'WS_CHANGE_VISIBLE_MARK';
const WS_CHANGE_COORDS_MARK = 'WS_CHANGE_COORDS_MARK';
const WS_ADD_MESSAGE_MARK = 'WS_ADD_MESSAGE_MARK';

export {
  RECORD_MARKS,
  ADD_MARK,
  DELETE_MARK,
  CHANGE_COORDS_MARK,
  CHANGE_VISIBLE_MARK,
  ADD_MESSAGE_MARK,
  RECORD_WEBSOCKET,
  RECORD_PSD_URL,
  RECORD_LAYERS,
  CHANGE_VISIBLE_LAYER,
  WS_ADD_MARK,
  WS_DELETE_MARK,
  WS_CHANGE_VISIBLE_MARK,
  WS_CHANGE_COORDS_MARK,
  WS_ADD_MESSAGE_MARK,
};
