export const RECORD_MARKS = 'RECORD_MARKS';
export const ADD_MARK = 'ADD_MARK';
export const DELETE_MARK = 'DELETE_MARK';
export const CHANGE_VISIBLE_MARK = 'CHANGE_VISIBLE_MARK';
export const CHANGE_COORDS_MARK = 'CHANGE_COORDS_MARK';
export const ADD_MESSAGE_MARK = 'ADD_MESSAGE_MARK';
export const DELETE_MESSAGE_MARK = 'DELETE_MESSAGE_MARK';
export const CLEAR_MARKS = 'CLEAR_MARKS';

export const RECORD_WEBSOCKET = 'RECORD_WEBSOCKET';

export const RECORD_PSD_URL = 'RECORD_PSD_URL';

export const RECORD_LAYERS = 'RECORD_PSD_LAYERS';
export const CHANGE_VISIBLE_LAYER = 'CHANGE_VISIBLE_LAYER';
export const CHANGE_VISIBLE_ALL_LAYERS = 'CHANGE_VISIBLE_ALL_LAYERS';
export const CLEAR_LAYERS = 'CLEAR_LAYERS';

export const WS_ADD_MARK = 'WS_ADD_MARK';
export const WS_DELETE_MARK = 'WS_DELETE_MARK';
export const WS_CHANGE_VISIBLE_MARK = 'WS_CHANGE_VISIBLE_MARK';
export const WS_CHANGE_COORDS_MARK = 'WS_CHANGE_COORDS_MARK';
export const WS_ADD_MESSAGE_MARK = 'WS_ADD_MESSAGE_MARK';
export const WS_DELETE_MESSAGE_MARK = 'WS_DELETE_MESSAGE_MARK';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
